#!/usr/bin/env python3
"""
Create Db2 tables required for saving /ai/orchestrate responses.
Run from backend dir: python scripts/init_db2_tables.py
Loads DB2_DSN from .env.
"""
from __future__ import annotations

import os
import sys

# Run from backend directory so app is on path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from dotenv import load_dotenv
load_dotenv()

def main():
    from app.db import db2
    if not db2.DB2_DSN:
        print("DB2_DSN not set. Add it to backend/.env")
        return 1
    if db2.ibm_db is None:
        print("ibm_db driver not available. pip install ibm_db")
        return 1

    conn = None
    try:
        conn = db2.ibm_db.connect(db2.DB2_DSN, "", "")
    except Exception as e:
        print("Failed to connect to Db2:", e)
        return 1

    def run(sql: str, ignore_exists: bool = False) -> bool:
        try:
            db2.ibm_db.exec_immediate(conn, sql)
            first_line = sql.strip().split("\n")[0]
            print("  OK:", first_line[:70] + ("..." if len(first_line) > 70 else ""))
            return True
        except Exception as e:
            err = str(e).upper()
            if ignore_exists:
                if "SQL0601" in err or "SQL0604" in err or "ALREADY EXISTS" in err or "DUPLICATE" in err:
                    print("  Skip (object already exists)")
                    return False
                if "SQL0159" in err or "DUPLICATE COLUMN" in err or "SQL0443" in err:
                    print("  Skip (column/object exists)")
                    return False
            print("  Error:", e)
            raise

    print("Creating tables in Db2...")
    try:
        # 1. questions (skip if exists)
        run("""
            CREATE TABLE questions (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                question_text VARCHAR(2048) NOT NULL,
                location VARCHAR(255) NOT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """, ignore_exists=True)
    except Exception:
        pass

    try:
        # 2. stakeholder_responses (skip if exists)
        run("""
            CREATE TABLE stakeholder_responses (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                question_id BIGINT NOT NULL,
                phase VARCHAR(50) NOT NULL DEFAULT 'legacy',
                stakeholder_id VARCHAR(100) NOT NULL,
                stakeholder_role VARCHAR(255) NOT NULL,
                ai_agent_id VARCHAR(100) NOT NULL,
                answer CHAR(3) NOT NULL,
                confidence DECIMAL(5, 2),
                reasoning CLOB,
                raw_payload CLOB,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT fk_question
                    FOREIGN KEY (question_id)
                    REFERENCES questions(id)
            )
        """, ignore_exists=True)
    except Exception:
        pass

    # 3. Add phase column if table exists but column doesn't
    try:
        run("ALTER TABLE stakeholder_responses ADD phase VARCHAR(50) DEFAULT 'legacy'", ignore_exists=True)
    except Exception:
        pass

    # 4. orchestrate_runs (skip if exists)
    try:
        run("""
            CREATE TABLE orchestrate_runs (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                question_id BIGINT NOT NULL,
                topic_reasoning CLOB,
                deep_analysis CLOB,
                assigned_agent_id VARCHAR(100),
                expertise_rationale CLOB,
                rag_context CLOB,
                context_for_agents CLOB,
                year INTEGER,
                model VARCHAR(100),
                full_response CLOB,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT fk_orchestrate_question
                    FOREIGN KEY (question_id)
                    REFERENCES questions(id)
            )
        """, ignore_exists=True)
    except Exception as e:
        print("orchestrate_runs:", e)

    # 5. Add new columns to orchestrate_runs if table already exists
    for col_sql in [
        "ALTER TABLE orchestrate_runs ADD context_for_agents CLOB",
        "ALTER TABLE orchestrate_runs ADD year INTEGER",
        "ALTER TABLE orchestrate_runs ADD model VARCHAR(100)",
    ]:
        try:
            run(col_sql, ignore_exists=True)
        except Exception:
            pass

    db2.ibm_db.commit(conn)
    db2.ibm_db.close(conn)
    print("Done.")
    return 0

if __name__ == "__main__":
    sys.exit(main())
