"""
IBM Db2 helpers for saving question runs and stakeholder AI perspectives.
"""

from __future__ import annotations

import json
import logging
import os
import sys
from contextlib import contextmanager
from dataclasses import dataclass
from typing import Any, Iterable, Literal

logger = logging.getLogger(__name__)

# --- IBM DB2 DLL Initialization (Windows) ---
# ibm_db requires clidriver/bin to be in the DLL search path on Windows.
if os.name == "nt":
    import site
    possible_paths = [
        os.path.join(site.getusersitepackages(), "clidriver", "bin"),
        # Hardcoded fallback for the current environment discovered during research
        r"C:\Users\tteth\AppData\Roaming\Python\Python314\site-packages\clidriver\bin",
    ]
    for path in possible_paths:
        if os.path.exists(path):
            try:
                # Use add_dll_directory for Python 3.8+
                os.add_dll_directory(path)
            except Exception:
                pass

try:
    import ibm_db
except ImportError as e:
    logger.warning(f"Could not load ibm_db driver: {e}. DB2 functionality will be unavailable.")
    ibm_db = None

logger = logging.getLogger(__name__)


DB2_DSN = os.getenv("DB2_DSN", "")


@dataclass
class StakeholderPerspective:
    """Single stakeholder AI response for a question."""

    stakeholder_id: str
    stakeholder_role: str
    ai_agent_id: str
    answer: Literal["yes", "no"]
    confidence: float | None = None
    reasoning: str | None = None
    location: str | None = None
    raw_payload: dict[str, Any] | None = None


@dataclass
class QuestionSummary:
    """Lightweight view of a question with simple yes/no counts."""

    id: int
    question_text: str
    location: str
    created_at: str
    yes_count: int
    no_count: int


@dataclass
class QuestionRow:
    """Full question row without aggregated counts."""

    id: int
    question_text: str
    location: str
    created_at: str


@dataclass
class StakeholderResponseRow:
    """Single stored stakeholder response row."""

    id: int
    question_id: int
    phase: str
    stakeholder_id: str
    stakeholder_role: str
    ai_agent_id: str
    answer: str
    confidence: float | None
    reasoning: str | None
    created_at: str


@contextmanager
def db2_connection():
    """
    Context manager that yields an ibm_db connection.

    Expects DB2_DSN in environment, e.g.:
        DATABASE=bludb;HOSTNAME=...;PORT=...;PROTOCOL=TCPIP;UID=...;PWD=...
    """
    if not DB2_DSN:
        raise RuntimeError("DB2_DSN environment variable is not set.")
    if ibm_db is None:
        raise RuntimeError(
            "The 'ibm_db' driver failed to load. On Windows, ensure 'clidriver/bin' "
            "is in your PATH or installed in site-packages."
        )

    conn = None
    try:
        conn = ibm_db.connect(DB2_DSN, "", "")
        yield conn
        ibm_db.commit(conn)
    except Exception:
        if conn is not None:
            try:
                ibm_db.rollback(conn)
            except Exception:  # pragma: no cover - defensive
                logger.exception("Failed to rollback Db2 transaction")
        logger.exception("Db2 operation failed")
        raise
    finally:
        if conn is not None:
            try:
                ibm_db.close(conn)
            except Exception:  # pragma: no cover - defensive
                logger.exception("Failed to close Db2 connection")


def _execute_many(
    conn,
    sql: str,
    params_seq: Iterable[tuple[Any, ...]],
) -> None:
    """
    Execute the same SQL with multiple parameter tuples.

    Db2's Python driver does not support executemany directly, so we loop.
    """
    stmt = ibm_db.prepare(conn, sql)
    for params in params_seq:
        ibm_db.execute(stmt, params)


# Schema expectations (create these in Db2; add phase and orchestrate_runs if missing):
#
#   CREATE TABLE questions (
#       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
#       question_text VARCHAR(2048) NOT NULL,
#       location VARCHAR(255) NOT NULL,
#       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
#   );
#
#   CREATE TABLE stakeholder_responses (
#       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
#       question_id BIGINT NOT NULL,
#       phase VARCHAR(50) NOT NULL DEFAULT 'legacy',
#       stakeholder_id VARCHAR(100) NOT NULL,
#       stakeholder_role VARCHAR(255) NOT NULL,
#       ai_agent_id VARCHAR(100) NOT NULL,
#       answer CHAR(3) NOT NULL,
#       confidence DECIMAL(5, 2),
#       reasoning CLOB,
#       raw_payload CLOB,
#       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
#       CONSTRAINT fk_question
#           FOREIGN KEY (question_id)
#           REFERENCES questions(id)
#   );
#
#   -- If phase column does not exist: ALTER TABLE stakeholder_responses ADD phase VARCHAR(50) DEFAULT 'legacy';
#
#   CREATE TABLE orchestrate_runs (
#       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
#       question_id BIGINT NOT NULL,
#       topic_reasoning CLOB,
#       deep_analysis CLOB,
#       assigned_agent_id VARCHAR(100),
#       expertise_rationale CLOB,
#       rag_context CLOB,
#       full_response CLOB,
#       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
#       CONSTRAINT fk_orchestrate_question
#           FOREIGN KEY (question_id)
#           REFERENCES questions(id)
#   );


def save_question_with_perspectives(
    question: str,
    location: str,
    perspectives: list[StakeholderPerspective],
) -> int:
    """
    Persist a single user question and all stakeholder AI perspectives.

    Returns the created question_id.
    """
    with db2_connection() as conn:
        question_id = _insert_question(conn, question, location)

        # Insert stakeholder responses (phase='legacy' for this path)
        insert_resp_sql = """
            INSERT INTO stakeholder_responses (
                question_id,
                phase,
                stakeholder_id,
                stakeholder_role,
                ai_agent_id,
                answer,
                confidence,
                reasoning,
                raw_payload
            )
            VALUES (?, 'legacy', ?, ?, ?, ?, ?, ?, ?)
        """

        if perspectives:
            params_seq: list[tuple[Any, ...]] = []
            for p in perspectives:
                answer_normalized = p.answer.lower()
                if answer_normalized not in {"yes", "no"}:
                    raise ValueError(f"Invalid answer value: {p.answer!r}")

                answer_db = "YES" if answer_normalized == "yes" else "NO"
                raw_json = json.dumps(p.raw_payload) if p.raw_payload is not None else None

                params_seq.append(
                    (
                        question_id,
                        p.stakeholder_id,
                        p.stakeholder_role,
                        p.ai_agent_id,
                        answer_db,
                        p.confidence,
                        p.reasoning,
                        raw_json,
                    )
                )

            _execute_many(conn, insert_resp_sql, params_seq)

        logger.info(
            "Saved question %s with %d stakeholder perspectives to Db2",
            question_id,
            len(perspectives),
        )

        _invalidate_db_cache()
        return question_id


def _insert_question(conn, question: str, location: str) -> int:
    """Insert a question row and return its new ID."""
    insert_q_sql = """
        INSERT INTO questions (question_text, location)
        VALUES (?, ?)
    """
    stmt = ibm_db.prepare(conn, insert_q_sql)
    ibm_db.execute(stmt, (question, location))

    id_stmt = ibm_db.exec_immediate(conn, "VALUES IDENTITY_VAL_LOCAL()")
    row = ibm_db.fetch_tuple(id_stmt)
    if not row:
        raise RuntimeError("Failed to retrieve generated question ID from Db2.")
    return int(row[0])


def create_question_only(question: str, location: str) -> int:
    """
    Create a question row without any stakeholder responses.

    Useful for frontends that collect the question/location first and attach
    stakeholder AI runs later.
    """
    with db2_connection() as conn:
        question_id = _insert_question(conn, question, location)
        logger.info("Created question %s (no stakeholder responses yet)", question_id)
        _invalidate_db_cache()
        return question_id


def _invalidate_db_cache() -> None:
    """Clear all DB read caches after a write operation."""
    from app.cache import cache_invalidate_namespace, NS_DB
    cache_invalidate_namespace(NS_DB)


def list_recent_questions(limit: int = 50) -> list[QuestionSummary]:
    """
    Return most recent questions with simple yes/no counts.  Cached in Redis.
    """
    from app.cache import cache_get, cache_set, NS_DB, TTL_DB_READ

    cache_key_parts = ("list_recent_questions", limit)
    cached = cache_get(NS_DB, *cache_key_parts)
    if cached is not None:
        return [QuestionSummary(**row) for row in cached]

    with db2_connection() as conn:
        sql = """
            SELECT
                q.id,
                q.question_text,
                q.location,
                CHAR(q.created_at) AS created_at,
                COALESCE(SUM(CASE WHEN r.answer = 'YES' THEN 1 ELSE 0 END), 0) AS yes_count,
                COALESCE(SUM(CASE WHEN r.answer = 'NO' THEN 1 ELSE 0 END), 0) AS no_count
            FROM questions q
            LEFT JOIN stakeholder_responses r
                ON r.question_id = q.id
            GROUP BY q.id, q.question_text, q.location, q.created_at
            ORDER BY q.created_at DESC
            FETCH FIRST ? ROWS ONLY
        """
        stmt = ibm_db.prepare(conn, sql)
        ibm_db.execute(stmt, (limit,))

        results: list[QuestionSummary] = []
        row = ibm_db.fetch_assoc(stmt)
        while row:
            results.append(
                QuestionSummary(
                    id=int(row["ID"]),
                    question_text=str(row["QUESTION_TEXT"]),
                    location=str(row["LOCATION"]),
                    created_at=str(row["CREATED_AT"]),
                    yes_count=int(row["YES_COUNT"]),
                    no_count=int(row["NO_COUNT"]),
                )
            )
            row = ibm_db.fetch_assoc(stmt)

        serializable = [
            {"id": r.id, "question_text": r.question_text, "location": r.location,
             "created_at": r.created_at, "yes_count": r.yes_count, "no_count": r.no_count}
            for r in results
        ]
        cache_set(NS_DB, *cache_key_parts, value=serializable, ttl=TTL_DB_READ)
        return results


def get_question_with_responses(
    question_id: int,
) -> tuple[QuestionRow, list[StakeholderResponseRow]]:
    """
    Load a single question and all of its stakeholder responses.  Cached in Redis.
    """
    from app.cache import cache_get, cache_set, NS_DB, TTL_DB_READ

    cache_key_parts = ("get_question_with_responses", question_id)
    cached = cache_get(NS_DB, *cache_key_parts)
    if cached is not None:
        q_data, resp_data = cached["question"], cached["responses"]
        question = QuestionRow(**q_data)
        responses = [StakeholderResponseRow(**r) for r in resp_data]
        return question, responses

    with db2_connection() as conn:
        # Question
        q_sql = """
            SELECT id, question_text, location, CHAR(created_at) AS created_at
            FROM questions
            WHERE id = ?
        """
        q_stmt = ibm_db.prepare(conn, q_sql)
        ibm_db.execute(q_stmt, (question_id,))
        q_row = ibm_db.fetch_assoc(q_stmt)
        if not q_row:
            raise ValueError(f"Question {question_id} not found.")

        question = QuestionRow(
            id=int(q_row["ID"]),
            question_text=str(q_row["QUESTION_TEXT"]),
            location=str(q_row["LOCATION"]),
            created_at=str(q_row["CREATED_AT"]),
        )

        # Responses (phase column optional for backward compatibility)
        r_sql = """
            SELECT
                id,
                question_id,
                COALESCE(phase, 'legacy') AS phase,
                stakeholder_id,
                stakeholder_role,
                ai_agent_id,
                answer,
                confidence,
                reasoning,
                CHAR(created_at) AS created_at
            FROM stakeholder_responses
            WHERE question_id = ?
            ORDER BY created_at ASC, id ASC
        """
        r_stmt = ibm_db.prepare(conn, r_sql)
        ibm_db.execute(r_stmt, (question_id,))

        responses: list[StakeholderResponseRow] = []
        r_row = ibm_db.fetch_assoc(r_stmt)
        while r_row:
            confidence_val = r_row["CONFIDENCE"]
            confidence = float(confidence_val) if confidence_val is not None else None
            responses.append(
                StakeholderResponseRow(
                    id=int(r_row["ID"]),
                    question_id=int(r_row["QUESTION_ID"]),
                    phase=str(r_row.get("PHASE", "legacy") or "legacy"),
                    stakeholder_id=str(r_row["STAKEHOLDER_ID"]),
                    stakeholder_role=str(r_row["STAKEHOLDER_ROLE"]),
                    ai_agent_id=str(r_row["AI_AGENT_ID"]),
                    answer=str(r_row["ANSWER"]),
                    confidence=confidence,
                    reasoning=str(r_row["REASONING"]) if r_row["REASONING"] is not None else None,
                    created_at=str(r_row["CREATED_AT"]),
                )
            )
            r_row = ibm_db.fetch_assoc(r_stmt)

        serializable = {
            "question": {
                "id": question.id, "question_text": question.question_text,
                "location": question.location, "created_at": question.created_at,
            },
            "responses": [
                {"id": r.id, "question_id": r.question_id, "phase": r.phase,
                 "stakeholder_id": r.stakeholder_id, "stakeholder_role": r.stakeholder_role,
                 "ai_agent_id": r.ai_agent_id, "answer": r.answer,
                 "confidence": r.confidence, "reasoning": r.reasoning,
                 "created_at": r.created_at}
                for r in responses
            ],
        }
        cache_set(NS_DB, *cache_key_parts, value=serializable, ttl=TTL_DB_READ)
        return question, responses


def save_orchestrate_response(question: str, location: str, response: dict[str, Any]) -> int:
    """
    Save a full /ai/orchestrate response to Db2 under one question.

    Creates: one question row, one orchestrate_runs row (topic_reasoning, deep_analysis,
    assigned_agent_id, expertise_rationale, rag_context, full_response JSON), and
    stakeholder_responses for each initial_bet (phase='initial_bet') and each
    triggered_agent (phase='triggered' with choice_reasoning, context, analysis in raw_payload).

    Returns the created question_id.
    """
    with db2_connection() as conn:
        question_id = _insert_question(conn, question, location)

        # Insert orchestrate_runs row (full run metadata + full JSON)
        topic_reasoning = response.get("topic_reasoning") or ""
        deep_analysis = response.get("deep_analysis") or ""
        assigned_agent_id = response.get("assigned_agent_id") or ""
        expertise_rationale = response.get("expertise_rationale") or ""
        rag_context = response.get("rag_context") or ""
        full_response = json.dumps(response)

        insert_run_sql = """
            INSERT INTO orchestrate_runs (
                question_id, topic_reasoning, deep_analysis,
                assigned_agent_id, expertise_rationale, rag_context, full_response
            )
            VALUES (?, ?, ?, ?, ?, ?, ?)
        """
        stmt = ibm_db.prepare(conn, insert_run_sql)
        ibm_db.execute(
            stmt,
            (
                question_id,
                topic_reasoning,
                deep_analysis,
                assigned_agent_id[:100] if assigned_agent_id else None,
                expertise_rationale,
                rag_context,
                full_response,
            ),
        )

        # Insert initial_bets as stakeholder_responses (phase='initial_bet')
        initial_bets = response.get("initial_bets") or []
        for bet in initial_bets:
            answer = (bet.get("answer") or "UNKNOWN").strip().upper()
            if answer not in ("YES", "NO"):
                answer = "NO"
            _insert_stakeholder_response(
                conn,
                question_id,
                phase="initial_bet",
                stakeholder_id=bet.get("agent_id") or "",
                stakeholder_role=bet.get("agent_name") or "",
                ai_agent_id=bet.get("agent_id") or "",
                answer=answer,
                confidence=bet.get("confidence"),
                reasoning=(bet.get("reasoning") or "")[:32700],
                raw_payload=None,
            )

        # Insert triggered_agents as stakeholder_responses (phase='triggered')
        triggered = response.get("triggered_agents") or []
        for t in triggered:
            answer = (t.get("answer") or "UNKNOWN").strip().upper()
            if answer not in ("YES", "NO"):
                answer = "NO"
            raw = {
                "choice_reasoning": t.get("choice_reasoning") or "",
                "context": t.get("context") or "",
                "analysis": t.get("analysis") or "",
            }
            _insert_stakeholder_response(
                conn,
                question_id,
                phase="triggered",
                stakeholder_id=t.get("agent_id") or "",
                stakeholder_role=t.get("agent_name") or "",
                ai_agent_id=t.get("agent_id") or "",
                answer=answer,
                confidence=t.get("confidence"),
                reasoning=(t.get("analysis") or "")[:32700],
                raw_payload=raw,
            )

        logger.info(
            "Saved orchestrate response for question %s: %d initial_bets, %d triggered_agents",
            question_id,
            len(initial_bets),
            len(triggered),
        )
        _invalidate_db_cache()
        return question_id


def _insert_stakeholder_response(
    conn,
    question_id: int,
    phase: str,
    stakeholder_id: str,
    stakeholder_role: str,
    ai_agent_id: str,
    answer: str,
    confidence: int | float | None,
    reasoning: str | None,
    raw_payload: dict[str, Any] | None,
) -> None:
    raw_json = json.dumps(raw_payload) if raw_payload is not None else None
    if reasoning and len(reasoning) > 32700:
        reasoning = reasoning[:32700]
    insert_sql = """
        INSERT INTO stakeholder_responses (
            question_id, phase, stakeholder_id, stakeholder_role,
            ai_agent_id, answer, confidence, reasoning, raw_payload
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
    """
    stmt = ibm_db.prepare(conn, insert_sql)
    ibm_db.execute(
        stmt,
        (
            question_id,
            phase[:50],
            stakeholder_id[:100],
            stakeholder_role[:255],
            ai_agent_id[:100],
            answer[:3],
            float(confidence) if confidence is not None else None,
            reasoning,
            raw_json,
        ),
    )


@dataclass
class OrchestrateRunRow:
    """One row from orchestrate_runs."""

    id: int
    question_id: int
    topic_reasoning: str
    deep_analysis: str
    assigned_agent_id: str | None
    expertise_rationale: str | None
    rag_context: str | None
    full_response: str | None
    created_at: str


def get_orchestrate_run(question_id: int) -> OrchestrateRunRow | None:
    """Load the orchestrate run for a question, if any.  Cached in Redis."""
    from app.cache import cache_get, cache_set, NS_DB, TTL_DB_READ

    cache_key_parts = ("get_orchestrate_run", question_id)
    cached = cache_get(NS_DB, *cache_key_parts)
    if cached is not None:
        return OrchestrateRunRow(**cached) if cached != "__none__" else None

    with db2_connection() as conn:
        sql = """
            SELECT id, question_id,
                   COALESCE(topic_reasoning, '') AS topic_reasoning,
                   COALESCE(deep_analysis, '') AS deep_analysis,
                   assigned_agent_id, expertise_rationale, rag_context,
                   full_response,
                   CHAR(created_at) AS created_at
            FROM orchestrate_runs
            WHERE question_id = ?
            ORDER BY created_at DESC
            FETCH FIRST 1 ROWS ONLY
        """
        stmt = ibm_db.prepare(conn, sql)
        ibm_db.execute(stmt, (question_id,))
        row = ibm_db.fetch_assoc(stmt)
        if not row:
            cache_set(NS_DB, *cache_key_parts, value="__none__", ttl=TTL_DB_READ)
            return None
        result = OrchestrateRunRow(
            id=int(row["ID"]),
            question_id=int(row["QUESTION_ID"]),
            topic_reasoning=str(row["TOPIC_REASONING"]),
            deep_analysis=str(row["DEEP_ANALYSIS"]),
            assigned_agent_id=str(row["ASSIGNED_AGENT_ID"]) if row.get("ASSIGNED_AGENT_ID") else None,
            expertise_rationale=str(row["EXPERTISE_RATIONALE"]) if row.get("EXPERTISE_RATIONALE") else None,
            rag_context=str(row["RAG_CONTEXT"]) if row.get("RAG_CONTEXT") else None,
            full_response=str(row["FULL_RESPONSE"]) if row.get("FULL_RESPONSE") else None,
            created_at=str(row["CREATED_AT"]),
        )
        serializable = {
            "id": result.id, "question_id": result.question_id,
            "topic_reasoning": result.topic_reasoning, "deep_analysis": result.deep_analysis,
            "assigned_agent_id": result.assigned_agent_id, "expertise_rationale": result.expertise_rationale,
            "rag_context": result.rag_context, "full_response": result.full_response,
            "created_at": result.created_at,
        }
        cache_set(NS_DB, *cache_key_parts, value=serializable, ttl=TTL_DB_READ)
        return result


