"""
IBM Db2 helpers for saving question runs and stakeholder AI perspectives.
"""

from __future__ import annotations

import json
import logging
import os
import sys
from contextlib import contextmanager
from dataclasses import dataclass
from typing import Any, Iterable, Literal

logger = logging.getLogger(__name__)

# --- IBM DB2 DLL Initialization (Windows) ---
# ibm_db requires clidriver/bin to be in the DLL search path on Windows.
if os.name == "nt":
    import site
    possible_paths = [
        os.path.join(site.getusersitepackages(), "clidriver", "bin"),
        # Hardcoded fallback for the current environment discovered during research
        r"C:\Users\tteth\AppData\Roaming\Python\Python314\site-packages\clidriver\bin",
    ]
    for path in possible_paths:
        if os.path.exists(path):
            try:
                # Use add_dll_directory for Python 3.8+
                os.add_dll_directory(path)
            except Exception:
                pass

try:
    import ibm_db
except ImportError as e:
    logger.warning(f"Could not load ibm_db driver: {e}. DB2 functionality will be unavailable.")
    ibm_db = None

logger = logging.getLogger(__name__)


DB2_DSN = os.getenv("DB2_DSN", "")


@dataclass
class StakeholderPerspective:
    """Single stakeholder AI response for a question."""

    stakeholder_id: str
    stakeholder_role: str
    ai_agent_id: str
    answer: Literal["yes", "no"]
    confidence: float | None = None
    reasoning: str | None = None
    location: str | None = None
    raw_payload: dict[str, Any] | None = None


@dataclass
class QuestionSummary:
    """Lightweight view of a question with simple yes/no counts."""

    id: int
    question_text: str
    location: str
    created_at: str
    yes_count: int
    no_count: int


@dataclass
class QuestionRow:
    """Full question row without aggregated counts."""

    id: int
    question_text: str
    location: str
    created_at: str


@dataclass
class StakeholderResponseRow:
    """Single stored stakeholder response row."""

    id: int
    question_id: int
    stakeholder_id: str
    stakeholder_role: str
    ai_agent_id: str
    answer: str
    confidence: float | None
    reasoning: str | None
    created_at: str


@contextmanager
def db2_connection():
    """
    Context manager that yields an ibm_db connection.

    Expects DB2_DSN in environment, e.g.:
        DATABASE=bludb;HOSTNAME=...;PORT=...;PROTOCOL=TCPIP;UID=...;PWD=...
    """
    if not DB2_DSN:
        raise RuntimeError("DB2_DSN environment variable is not set.")
    if ibm_db is None:
        raise RuntimeError(
            "The 'ibm_db' driver failed to load. On Windows, ensure 'clidriver/bin' "
            "is in your PATH or installed in site-packages."
        )

    conn = None
    try:
        conn = ibm_db.connect(DB2_DSN, "", "")
        yield conn
        ibm_db.commit(conn)
    except Exception:
        if conn is not None:
            try:
                ibm_db.rollback(conn)
            except Exception:  # pragma: no cover - defensive
                logger.exception("Failed to rollback Db2 transaction")
        logger.exception("Db2 operation failed")
        raise
    finally:
        if conn is not None:
            try:
                ibm_db.close(conn)
            except Exception:  # pragma: no cover - defensive
                logger.exception("Failed to close Db2 connection")


def _execute_many(
    conn,
    sql: str,
    params_seq: Iterable[tuple[Any, ...]],
) -> None:
    """
    Execute the same SQL with multiple parameter tuples.

    Db2's Python driver does not support executemany directly, so we loop.
    """
    stmt = ibm_db.prepare(conn, sql)
    for params in params_seq:
        ibm_db.execute(stmt, params)


def save_question_with_perspectives(
    question: str,
    location: str,
    perspectives: list[StakeholderPerspective],
) -> int:
    """
    Persist a single user question and all stakeholder AI perspectives.

    Returns the created question_id.

    Schema expectations (you should create these in Db2):

        CREATE TABLE questions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            question_text VARCHAR(2048) NOT NULL,
            location VARCHAR(255) NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE stakeholder_responses (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            question_id BIGINT NOT NULL,
            stakeholder_id VARCHAR(100) NOT NULL,
            stakeholder_role VARCHAR(255) NOT NULL,
            ai_agent_id VARCHAR(100) NOT NULL,
            answer CHAR(3) NOT NULL,
            confidence DECIMAL(5, 2),
            reasoning CLOB,
            raw_payload CLOB,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT fk_question
                FOREIGN KEY (question_id)
                REFERENCES questions(id)
        );
    """
    with db2_connection() as conn:
        question_id = _insert_question(conn, question, location)

        # Insert stakeholder responses
        insert_resp_sql = """
            INSERT INTO stakeholder_responses (
                question_id,
                stakeholder_id,
                stakeholder_role,
                ai_agent_id,
                answer,
                confidence,
                reasoning,
                raw_payload
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
        """

        if perspectives:
            params_seq: list[tuple[Any, ...]] = []
            for p in perspectives:
                answer_normalized = p.answer.lower()
                if answer_normalized not in {"yes", "no"}:
                    raise ValueError(f"Invalid answer value: {p.answer!r}")

                answer_db = "YES" if answer_normalized == "yes" else "NO"
                raw_json = json.dumps(p.raw_payload) if p.raw_payload is not None else None

                params_seq.append(
                    (
                        question_id,
                        p.stakeholder_id,
                        p.stakeholder_role,
                        p.ai_agent_id,
                        answer_db,
                        p.confidence,
                        p.reasoning,
                        raw_json,
                    )
                )

            _execute_many(conn, insert_resp_sql, params_seq)

        logger.info(
            "Saved question %s with %d stakeholder perspectives to Db2",
            question_id,
            len(perspectives),
        )

        return question_id


def _insert_question(conn, question: str, location: str) -> int:
    """Insert a question row and return its new ID."""
    insert_q_sql = """
        INSERT INTO questions (question_text, location)
        VALUES (?, ?)
    """
    stmt = ibm_db.prepare(conn, insert_q_sql)
    ibm_db.execute(stmt, (question, location))

    id_stmt = ibm_db.exec_immediate(conn, "VALUES IDENTITY_VAL_LOCAL()")
    row = ibm_db.fetch_tuple(id_stmt)
    if not row:
        raise RuntimeError("Failed to retrieve generated question ID from Db2.")
    return int(row[0])


def create_question_only(question: str, location: str) -> int:
    """
    Create a question row without any stakeholder responses.

    Useful for frontends that collect the question/location first and attach
    stakeholder AI runs later.
    """
    with db2_connection() as conn:
        question_id = _insert_question(conn, question, location)
        logger.info("Created question %s (no stakeholder responses yet)", question_id)
        return question_id


def list_recent_questions(limit: int = 50) -> list[QuestionSummary]:
    """
    Return most recent questions with simple yes/no counts.
    """
    with db2_connection() as conn:
        sql = """
            SELECT
                q.id,
                q.question_text,
                q.location,
                CHAR(q.created_at) AS created_at,
                COALESCE(SUM(CASE WHEN r.answer = 'YES' THEN 1 ELSE 0 END), 0) AS yes_count,
                COALESCE(SUM(CASE WHEN r.answer = 'NO' THEN 1 ELSE 0 END), 0) AS no_count
            FROM questions q
            LEFT JOIN stakeholder_responses r
                ON r.question_id = q.id
            GROUP BY q.id, q.question_text, q.location, q.created_at
            ORDER BY q.created_at DESC
            FETCH FIRST ? ROWS ONLY
        """
        stmt = ibm_db.prepare(conn, sql)
        ibm_db.execute(stmt, (limit,))

        results: list[QuestionSummary] = []
        row = ibm_db.fetch_assoc(stmt)
        while row:
            results.append(
                QuestionSummary(
                    id=int(row["ID"]),
                    question_text=str(row["QUESTION_TEXT"]),
                    location=str(row["LOCATION"]),
                    created_at=str(row["CREATED_AT"]),
                    yes_count=int(row["YES_COUNT"]),
                    no_count=int(row["NO_COUNT"]),
                )
            )
            row = ibm_db.fetch_assoc(stmt)

        return results


def get_question_with_responses(
    question_id: int,
) -> tuple[QuestionRow, list[StakeholderResponseRow]]:
    """
    Load a single question and all of its stakeholder responses.
    """
    with db2_connection() as conn:
        # Question
        q_sql = """
            SELECT id, question_text, location, CHAR(created_at) AS created_at
            FROM questions
            WHERE id = ?
        """
        q_stmt = ibm_db.prepare(conn, q_sql)
        ibm_db.execute(q_stmt, (question_id,))
        q_row = ibm_db.fetch_assoc(q_stmt)
        if not q_row:
            raise ValueError(f"Question {question_id} not found.")

        question = QuestionRow(
            id=int(q_row["ID"]),
            question_text=str(q_row["QUESTION_TEXT"]),
            location=str(q_row["LOCATION"]),
            created_at=str(q_row["CREATED_AT"]),
        )

        # Responses
        r_sql = """
            SELECT
                id,
                question_id,
                stakeholder_id,
                stakeholder_role,
                ai_agent_id,
                answer,
                confidence,
                reasoning,
                CHAR(created_at) AS created_at
            FROM stakeholder_responses
            WHERE question_id = ?
            ORDER BY created_at ASC, id ASC
        """
        r_stmt = ibm_db.prepare(conn, r_sql)
        ibm_db.execute(r_stmt, (question_id,))

        responses: list[StakeholderResponseRow] = []
        r_row = ibm_db.fetch_assoc(r_stmt)
        while r_row:
            confidence_val = r_row["CONFIDENCE"]
            confidence = float(confidence_val) if confidence_val is not None else None
            responses.append(
                StakeholderResponseRow(
                    id=int(r_row["ID"]),
                    question_id=int(r_row["QUESTION_ID"]),
                    stakeholder_id=str(r_row["STAKEHOLDER_ID"]),
                    stakeholder_role=str(r_row["STAKEHOLDER_ROLE"]),
                    ai_agent_id=str(r_row["AI_AGENT_ID"]),
                    answer=str(r_row["ANSWER"]),
                    confidence=confidence,
                    reasoning=str(r_row["REASONING"]) if r_row["REASONING"] is not None else None,
                    created_at=str(r_row["CREATED_AT"]),
                )
            )
            r_row = ibm_db.fetch_assoc(r_stmt)

        return question, responses


